sudo: required
dist: trusty

language: cpp

cache:
  directories:
    - $HOME/travisCacheDir

env:
  matrix:
   - BUILD_VERSION=""
   - BUILD_VERSION="disable_autoupdate"
   - BUILD_VERSION="disable_register_custom_scheme"
   - BUILD_VERSION="disable_crash_reports"
   - BUILD_VERSION="disable_network_proxy"
   - BUILD_VERSION="disable_desktop_file_generation"
   - BUILD_VERSION="disable_unity_integration"

matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - bison
      - build-essential
      - cmake
      - devscripts
      - dpatch
      - equivs
      - fakeroot
      - g++-6
      - gcc-6
      - git
      - gnome-common
      - gobject-introspection
      - gtk-doc-tools
      - libappindicator-dev
      - libasound2-dev
      - libdbusmenu-glib-dev
      - liblzma-dev
      - libopus-dev
      - libpulse-dev
      - libssl-dev
      - libunity-dev
      - libva-dev
      - libvdpau-dev
      - libxcb-xkb-dev
      - libxkbcommon-dev
      - lintian
      - quilt
      - valac
      - xutils-dev
      - yasm

before_install:
  - "export TRAVIS_COMMIT_MSG=\"$(git log --format=%B --no-merges -n 1)\""
  - .travis/check.sh
  - export CXX="g++-6" CC="gcc-6"
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
  - sudo update-alternatives --config gcc
  - g++ --version

script:
  - .travis/build.sh
